# Generated by Django 3.0.6 on 2021-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
