# Generated by Django 3.0.6 on 2021-01-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otherinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherInformation',
            new_name='Informations',
        ),
    ]
