# Generated by Django 3.0.6 on 2021-01-22 00:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210118_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_receptionist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20, verbose_name='Imię')),
                ('Surname', models.CharField(max_length=30, verbose_name='nazwisko')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi zawierać od 9-15 znaków i pierwszym znakiem może być +', regex='^\\+?1?\\d{9,15}$')])),
                ('account', models.OneToOneField(blank=True, limit_choices_to={'is_receptionist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ManyToManyField(to='account.Dentist')),
            ],
        ),
    ]
