# Generated by Django 3.0.6 on 2021-01-22 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210122_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='account',
            field=models.OneToOneField(limit_choices_to={'is_receptionist': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
