# Generated by Django 3.0.6 on 2021-01-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210122_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='wysłane o godzinie')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Dentist')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Receptionist')),
            ],
        ),
    ]
