# Generated by Django 3.0.6 on 2021-01-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210127_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='receptionist',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='dentist',
            field=models.ManyToManyField(to='account.Dentist'),
        ),
    ]
