# Generated by Django 3.0.6 on 2021-02-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210127_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_hours_open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='godzina otwarcia')),
                ('end_hour', models.TimeField(verbose_name='godzina zamknięcia')),
                ('open_days', models.TextField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('5', 'Piątke'), ('6', 'Sobota'), ('7', 'Niedziela')])),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Dentist')),
            ],
        ),
    ]
