# Generated by Django 3.0.6 on 2021-02-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_day_hours_open'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day_hours_open',
            new_name='WeekdayHoursOpen',
        ),
    ]
