# Generated by Django 3.0.6 on 2021-02-03 17:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210203_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdayhoursopen',
            name='open_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('5', 'Piątke'), ('6', 'Sobota'), ('7', 'Niedziela')], max_length=13),
        ),
    ]
