# Generated by Django 3.0.6 on 2021-02-06 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210205_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='receptionist',
            field=models.ManyToManyField(to='account.Receptionist'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='dentist',
        ),
        migrations.AddField(
            model_name='location',
            name='dentist',
            field=models.ManyToManyField(to='account.Dentist'),
        ),
    ]
