# Generated by Django 3.0.6 on 2021-02-06 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210206_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_to_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='wysłane o godzinie')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
