# Generated by Django 3.0.6 on 2021-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_invitation_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Placówka', max_length=50),
            preserve_default=False,
        ),
    ]
