# Generated by Django 3.0.6 on 2021-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210210_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dentist',
            field=models.ManyToManyField(to='account.Dentist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='receptionist',
            field=models.ManyToManyField(to='account.Receptionist'),
        ),
    ]
