# Generated by Django 3.0.6 on 2021-02-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20210210_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizyta_kontrolna', models.IntegerField()),
                ('wyrywanie', models.IntegerField()),
                ('kanałowe', models.IntegerField()),
                ('plomba', models.IntegerField()),
                ('czyszczenie', models.IntegerField()),
                ('leczenie_długotrwałe', models.IntegerField()),
                ('lekarstwo', models.IntegerField()),
                ('operacja', models.IntegerField()),
                ('inne', models.IntegerField()),
            ],
        ),
    ]
