# Generated by Django 3.0.6 on 2021-02-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_cennik_dentist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='creator',
        ),
    ]
