# Generated by Django 3.0.6 on 2021-02-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210212_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiadomosc',
            old_name='target',
            new_name='nowy_cel',
        ),
    ]
