# Generated by Django 3.0.6 on 2021-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210212_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiadomosc',
            name='special_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
