# Generated by Django 3.0.6 on 2021-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_wiadomosc_special_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosc',
            name='special_data',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
