# Generated by Django 3.0.6 on 2021-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20210212_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersites',
            name='dentist',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='OtherSites',
        ),
    ]
