# Generated by Django 3.0.6 on 2020-12-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tooth', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_visit', models.DateField(verbose_name='Dzień zaplanowanej wizyty')),
                ('time_of_the_visit', models.TimeField(verbose_name='Godzina zaplanowanej wizyty')),
                ('time_end_visit', models.TimeField(verbose_name='Godzina końca wizyty')),
                ('status', models.CharField(choices=[('zaplanowana', 'Wizyta jest zaplanowana'), ('odbyła sie', 'Wizyta się odbyła'), (' zmiana daty', 'Data wizyty musi zostać zmieniona'), ('nie potwierdzona', 'Wizyta nie jest zatwierdzona'), ('odwołana', 'odwołana'), ('odwołana przez pacjenta', 'odwołane przez pacjenta'), ('do zatwierdzenia przez pacjenta', 'do zatwierdzenia przez pacjenta'), ('zmiana daty przez pacjenta', 'zmiana daty przez pacjenta')], default='zaplanowana', max_length=50)),
                ('Type_of', models.CharField(choices=[('wizyta kontrolna', 'wizyta kontrolna'), ('leczenie', 'leczenie'), ('wyrywanie', 'wyrywanie')], default='leczenie', max_length=20)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='opis przebiegu wizyty')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='zapłata za wizytę')),
                ('Dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Dentist')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
                ('Tooth_Repaired', models.ManyToManyField(blank=True, to='tooth.Tooth', verbose_name='Zęby naprawiane lub wyleczone ')),
            ],
        ),
        migrations.CreateModel(
            name='Visit_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='opis przebiegu wizyty')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='zapłata za wizytę')),
                ('Tooth_Repaired', models.ManyToManyField(to='tooth.Tooth', verbose_name='Zęby naprawiane lub wyleczone ')),
                ('Visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visit.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='tooth_healing_destruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.TextField(blank=True, choices=[('kanałowe', 'Kanałowe'), ('plomba', 'Plomba'), ('czyszczenie', 'Czyszczenie'), ('inne', 'Inne'), ('leczenie długotrwałe', 'Leczenie Długotrwałe'), ('lekarstwo', 'Lekarstwo'), ('operacja', 'Operacja')], null=True)),
                ('about_healing', models.TextField(blank=True, null=True)),
                ('date_of_fixing', models.DateTimeField(blank=True, null=True)),
                ('tooth_destructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooth.Tooth_destructions')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.DateTimeField()),
                ('type_of', models.TextField(choices=[('zatwierdzenie', 'Zatwierdzone'), ('odwołanie', 'Odwołanie'), ('zmiana daty', 'Zmieniona'), ('usunięta', 'Usunięta'), ('przypomnienie', 'Przypomnienie'), ('czat', 'Czat'), ('zaproszenie', 'Zaproszenie'), ('ogólne', 'Ogólne')])),
                ('read', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('target', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
