# Generated by Django 3.0.6 on 2020-12-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth_healing_destruction',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Dentist'),
        ),
    ]
