# Generated by Django 3.0.6 on 2020-12-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_tooth_healing_destruction_dentist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit_Details',
        ),
    ]
