# Generated by Django 3.0.6 on 2021-01-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20210118_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='cel',
        ),
    ]
