# Generated by Django 3.0.6 on 2021-01-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_remove_information_cel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
