# Generated by Django 3.0.6 on 2020-12-08 17:58

from django.db import migrations, models
import django.db.models.deletion
import tooth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Jedynka'), (2, 'Dwójka'), (3, 'Trójka'), (4, 'Czwórka'), (5, 'Piątka'), (6, 'Szóstka'), (7, 'Siódemka'), (8, 'Ósemka')])),
                ('level', models.TextField(choices=[('górny', 'Górna'), ('dolny', 'Dolna')])),
                ('side', models.TextField(choices=[('lewy', 'Lewa'), ('prawy', 'Prawa')])),
                ('tooth_type', models.TextField(choices=[('stały', 'Stały'), ('mleczny', 'Mleczny')])),
                ('exists', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Tooth_rentgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=tooth.models.all_tooth_rentgen_images)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooth.Tooth')),
            ],
        ),
        migrations.CreateModel(
            name='Tooth_destructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('1', 'Bardzo Małe'), ('2', 'Małe'), ('3', 'Średnie'), ('4', 'Duże'), ('5', 'Bardzo Duże')])),
                ('depth', models.IntegerField()),
                ('side', models.TextField(choices=[('left', 'Lewa'), ('right', 'Prawa')])),
                ('front', models.TextField(choices=[('front', 'Przód'), ('back', 'Tył')])),
                ('date_of_finding', models.DateTimeField(auto_now_add=True)),
                ('healed', models.BooleanField(default=False)),
                ('planned_healing', models.BooleanField(default=False)),
                ('type_of', models.TextField(blank=True, choices=[('kanałowe', 'Kanałowe'), ('plomba', 'Plomba'), ('czyszczenie', 'Czyszczenie'), ('inne', 'Inne'), ('leczenie długotrwałe', 'Leczenie Długotrwałe'), ('lekarstwo', 'Lekarstwo'), ('operacja', 'Operacja')], null=True)),
                ('date_of_fixing', models.DateField(blank=True, null=True)),
                ('about_healing', models.TextField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('visit_id', models.IntegerField(blank=True, null=True)),
                ('healed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Dentist')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooth.Tooth')),
            ],
        ),
    ]
