# Generated by Django 3.0.6 on 2020-12-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooth_destructions',
            name='about_healing',
        ),
        migrations.RemoveField(
            model_name='tooth_destructions',
            name='date_of_fixing',
        ),
        migrations.RemoveField(
            model_name='tooth_destructions',
            name='log',
        ),
        migrations.RemoveField(
            model_name='tooth_destructions',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='tooth_destructions',
            name='visit_id',
        ),
    ]
