# Generated by Django 3.0.6 on 2020-12-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooth', '0002_auto_20201217_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooth_destructions',
            name='healed_by',
        ),
    ]
