# Generated by Django 3.0.6 on 2021-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooth', '0004_tooth_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
    ]
