# Generated by Django 3.0.6 on 2021-01-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooth', '0005_tooth_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth',
            name='status',
            field=models.TextField(choices=[('zdrowy', 'Zdrowy'), ('chory', 'Chory'), ('wyleczony', 'Wyleczony')], default='zdrowy'),
        ),
    ]
